version: '3.5'

volumes:
  dbdata:
    name: romweb_dbdata
    external: true

services:
  db:
    image: "postgres:alpine"
    env_file: backend/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"
    ports:
    - "6379:6379"

  frontend:
    build:
      dockerfile: frontend/Dockerfile.dev
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: backend/Dockerfile.dev
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
      - ./backend/media:/home/user/app/backend/media
    env_file: backend/.env.dev
    depends_on:
      - db
      - broker
      - result
      - frontend

  celery:
    build:
      dockerfile: backend/Dockerfile.dev
      context: .
    command: celery --app=romweb worker --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env.dev
    depends_on:
      - db
      - broker
      - result

  mailhog: # service for faking a SMTP server
    image: mailhog/mailhog
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui

# tools
  masquerade:
    build:
      context: ./backend/tools/services/masquerade
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./backend/tools/services/masquerade:/app
    command: uvicorn main:app --host 0.0.0.0 --port 5005 --reload

  stringutils:
    build:
      context: ./backend/tools/services/stringutils
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    volumes:
      - ./backend/tools/services/stringutils:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 5010 --reload
