version: '3.5'

networks:
  romweb_dev_network:
    external: true

volumes:
  dbdata:
    name: romweb_dbdata
    external: true

services:
  db:
    image: "postgres:alpine"
    env_file: backend/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated
    networks:
      - romweb_dev_network

  broker:
    image: "rabbitmq:alpine"
    networks:
      - romweb_dev_network

  result:
    image: "redis:alpine"
    ports:
    - "6379:6379"
    networks:
      - romweb_dev_network

  frontend:
    build:
      dockerfile: frontend/Dockerfile.dev
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - romweb_dev_network

  backend:
    build:
      dockerfile: backend/Dockerfile.dev
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
      - ./backend/media:/home/user/app/backend/media
    env_file: backend/.env.dev
    depends_on:
      - db
      - broker
      - result
      - frontend
    networks:
      - romweb_dev_network

  celery:
    build:
      dockerfile: backend/Dockerfile.dev
      context: .
    command: celery --app=romweb worker --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env.dev
    depends_on:
      - db
      - broker
      - result
    networks:
      - romweb_dev_network

  celery-beat:
    build:
      dockerfile: backend/Dockerfile.dev
      context: .
    command: celery --app=romweb beat --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env.dev
    depends_on:
      - db
      - broker
      - result
    networks:
      - romweb_dev_network

  mailhog: # service for faking a SMTP server
    image: mailhog/mailhog
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui
    networks:
      - romweb_dev_network

# tools
#  masquerade:
#    build:
#      context: ./backend/tools/services/masquerade
#      dockerfile: Dockerfile
#    ports:
#      - "5005:5005"
#    volumes:
#      - ./backend/tools/services/masquerade:/app
#    networks:
#      - romweb_dev_network
#    command: uvicorn main:app --host 0.0.0.0 --port 5005 --reload
#
