version: '3.5'

volumes:
  dbdata:
    name: romweb_dbdata
    external: true

services:
  db:
    image: "postgres:alpine"
    env_file: backend/.env.prod
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"
    ports:
    - "6379:6379"

  frontend:
    build:
      dockerfile: frontend/Dockerfile.prod
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: backend/Dockerfile.prod
      context: .
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
    ports:
      - "8000-8001:8000"
    volumes:
      - ./:/home/user/app/
      - ./backend/media:/home/user/app/backend/media
    env_file: backend/.env.prod
    depends_on:
      - db
      - broker
      - result
      - frontend

  celery:
    build:
      dockerfile: backend/Dockerfile.prod
      context: .
    command: celery --app=romweb worker --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env.prod
    depends_on:
      - db
      - broker
      - result

  # tools
  charcount:
    build:
      context: ./backend/tools/services/charcount
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  masquerade:
    build:
      context: ./backend/tools/services/masquerade
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./backend/tools/services/masquerade:/app
