volumes:
  dbdata:
    name: romweb_dbdata
    external: true
  redisdata:

services:
  db:
    image: "postgres:alpine"
    env_file: backend/.env.prod
    volumes:
      - dbdata:/var/lib/postgresql/data:delegated

  broker:
    image: "rabbitmq:alpine"

  result:
    image: "redis:alpine"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  frontend:
    build:
      dockerfile: frontend/Dockerfile.prod
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: backend/Dockerfile.prod
      context: .
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
    ports:
      - "8000-8001:8000"
    volumes:
      - ./:/home/user/app/
      - ./backend/media:/home/user/app/backend/media
    env_file: backend/.env.prod
    depends_on:
      - db
      - broker
      - result
      - frontend

  celery:
    build:
      dockerfile: backend/Dockerfile.prod
      context: .
    command: celery --app=romweb worker --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env.prod
    depends_on:
      - db
      - broker
      - result

  celery-beat:
    build:
      dockerfile: backend/Dockerfile.prod
      context: .
    command: celery --app=romweb beat --loglevel=info
    volumes:
      - ./:/home/user/app/
    env_file: backend/.env.prod
    depends_on:
      - db
      - broker
      - result
