# Generated by Django 5.2.9 on 2025-12-16 16:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no momento.",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data/hora em que o registro entrou em vigor.",
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora de encerramento do registro, se houver.",
                        null=True,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do serviço oferecido no catálogo.",
                        max_length=100,
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do serviço exibida para o cliente.",
                    ),
                ),
                (
                    "preco_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preço base do serviço.",
                        max_digits=8,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Parceria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no momento.",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data/hora em que o registro entrou em vigor.",
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora de encerramento do registro, se houver.",
                        null=True,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da pessoa física ou jurídica parceira.",
                        max_length=100,
                    ),
                ),
                (
                    "natureza",
                    models.CharField(
                        choices=[("pf", "Pessoa Física"), ("pj", "Pessoa Jurídica")],
                        help_text="Indica se a parceria é pessoa física ou pessoa jurídica.",
                        max_length=2,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("cliente", "Cliente"),
                            ("marca", "Marca"),
                            ("conteudo", "Criador de conteúdo"),
                            ("tecnologia", "Tecnologia"),
                            ("fornecedor", "Fornecedor"),
                            ("distribuidor", "Distribuidor"),
                            ("social", "Social"),
                            ("comunidade", "Comunidade"),
                        ],
                        help_text="Classificação da relação comercial.",
                        max_length=20,
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        blank=True,
                        help_text="Domímio personalizado do cliente, se houver.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "proprietario",
                    models.ForeignKey(
                        help_text="Usuário principal responsável pela parceria.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcerias_proprietario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContratoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no momento.",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data/hora em que o registro entrou em vigor.",
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora de encerramento do registro, se houver.",
                        null=True,
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Notas gerais sobre o contrato, ou termos específicos.",
                    ),
                ),
                (
                    "parceria",
                    models.ForeignKey(
                        help_text="Parceria a qual o contrato pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="parceria.parceria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de Serviço",
                "verbose_name_plural": "Contratos de Serviço",
            },
        ),
        migrations.CreateModel(
            name="PedidoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no momento.",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data/hora em que o registro entrou em vigor.",
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora de encerramento do registro, se houver.",
                        null=True,
                    ),
                ),
                (
                    "status_pedido_servico",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        help_text="Status atual do pedido dentro do fluxo operacional.",
                        max_length=20,
                    ),
                ),
                (
                    "parceria",
                    models.ForeignKey(
                        help_text="Parceria que abriu o pedido de serviço.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedidos",
                        to="parceria.parceria",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.CreateModel(
            name="PedidoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_renovacao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data prevista para renovação, se aplicável.",
                        null=True,
                    ),
                ),
                (
                    "recorrente",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o serviço deve ser renovado.",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        help_text="Pedido ao qual este item pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="parceria.pedidoservico",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        help_text="Serviço solicitado neste item.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parceria.servico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicoContratado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no momento.",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data/hora em que o registro entrou em vigor.",
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora de encerramento do registro, se houver.",
                        null=True,
                    ),
                ),
                (
                    "recorrente",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se serviço possui renovação periódica.",
                    ),
                ),
                (
                    "contrato_servico",
                    models.ForeignKey(
                        help_text="Contrato ao qual este serviço contratado está vínculado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos_contratados",
                        to="parceria.contratoservico",
                    ),
                ),
                (
                    "pedido_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item de pedido que originou este serviço, usado para auditoria.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicos_contratados",
                        to="parceria.pedidoitem",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        help_text="Serviço adquirido pelo cliente dentro deste contrato.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos_contratados",
                        to="parceria.servico",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContratoCobranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor a ser cobrado do cliente.",
                        max_digits=10,
                    ),
                ),
                (
                    "vencimento",
                    models.DateField(help_text="Data de vencimento da cobrança."),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a cobrança foi paga, se houver.",
                        null=True,
                    ),
                ),
                (
                    "servico_contratado",
                    models.ForeignKey(
                        help_text="Serviço contratado a qual pertence esta cobrança.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cobrancas",
                        to="parceria.servicocontratado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketSuporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_ticket_suporte",
                    models.CharField(
                        choices=[
                            ("sugestao", "Sugestão de funcionalidade"),
                            ("ajuda", "Ajuda ou dúvida"),
                            ("problema", "Relato de problema"),
                            ("outro", "Outro"),
                        ],
                        help_text="Tipo de solicitação.",
                        max_length=20,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título curto da solicitação", max_length=120
                    ),
                ),
                (
                    "descricao",
                    models.TextField(help_text="Descrição detalhada da solicitação."),
                ),
                (
                    "status_ticket_suporte",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("em_analise", "Em análise"),
                            ("em_execucao", "Em execução"),
                            ("concluido", "Concluído"),
                            ("rejeitado", "Rejeitado"),
                        ],
                        default="novo",
                        help_text="Status atual do ticket.",
                        max_length=20,
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data/hora em que o ticket foi criado.",
                    ),
                ),
                (
                    "prazo_entrega",
                    models.DateTimeField(
                        blank=True,
                        help_text="Prazo estimado para resolução, se definido.",
                        null=True,
                    ),
                ),
                (
                    "parceria",
                    models.ForeignKey(
                        help_text="Parceria que abriu o ticket.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parceria.parceria",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tickets",
            },
        ),
        migrations.CreateModel(
            name="TicketMensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(help_text="Conteúdo da mensagem enviada."),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data/hora em que a mensagem foi registrada.",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        help_text="Usuário que escreveu a mensagem.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        help_text="Ticket ao qual a mensagem pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="parceria.ticketsuporte",
                    ),
                ),
            ],
            options={
                "ordering": ["data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="ParceriaMembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo no momento.",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Data/hora em que o registro entrou em vigor.",
                    ),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora de encerramento do registro, se houver.",
                        null=True,
                    ),
                ),
                (
                    "parceria",
                    models.ForeignKey(
                        help_text="Parceria a qual o membro pertence.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros",
                        to="parceria.parceria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário membro colaborador.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcerias_membro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro de Parceria",
                "verbose_name_plural": "Membros de Parceria",
                "unique_together": {("parceria", "usuario")},
            },
        ),
    ]
