# Generated by Django 5.2 on 2025-04-08 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("conversao", "Conversão"),
                            ("gerador", "Gerador"),
                            ("validacao", "Validacão"),
                            ("calculadora", "Calculadora"),
                            ("simulador", "Simulador"),
                            ("codificacao", "Codificação"),
                            ("tradutor", "Tradutor"),
                            ("utilitario", "Utilitário Geral"),
                        ],
                        default="utilitario",
                        max_length=50,
                    ),
                ),
                ("api_url", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ToolField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                (
                    "io_type",
                    models.CharField(
                        choices=[("input", "Entrada"), ("output", "Saída")],
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "Texto simples"),
                            ("int", "Número inteiro"),
                            ("float", "Número decimal"),
                            ("bool", "Booleano"),
                            ("list", "Lista"),
                            ("dict", "Dicionário"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("text", "Área de texto"),
                            ("input", "Campo de entrada"),
                            ("checkbox", "Caixa de seleção"),
                            ("select", "Dropdown"),
                            ("radio", "Botões de opção"),
                        ],
                        default="input",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("help_text", models.CharField(blank=True, max_length=255)),
                ("default_value", models.CharField(blank=True, max_length=255)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "ordering": ["tool", "io_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="ToolFieldOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                ("label", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="tools.toolfield",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
