# Generated by Django 5.2 on 2025-04-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('conversao', 'Conversão'), ('gerador', 'Gerador'), ('validacao', 'Validacão'), ('calculadora', 'Calculadora'), ('simulador', 'Simulador'), ('codificacao', 'Codificação'), ('tradutor', 'Tradutor'), ('utilitario', 'Utilitário Geral')], default='utilitario', max_length=50),
        ),
        migrations.CreateModel(
            name='ToolIOField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('io_type', models.CharField(choices=[('input', 'Entrada'), ('output', 'Saída')], max_length=20)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('checkbox', 'Caixa de seleção'), ('select', 'Seleção')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='io_fields', to='tools.tool')),
            ],
        ),
        migrations.CreateModel(
            name='ToolIOOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('io_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tools.tooliofield')),
            ],
        ),
    ]
