# Generated by Django 5.2.3 on 2025-06-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_robotstxt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('hire', 'Contratação'), ('collab', 'Parceria'), ('feedback', 'Feedback'), ('question', 'Dúvida'), ('other', 'Outro')], max_length=50)),
                ('message', models.TextField(max_length=4000)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Contato Profissional',
                'verbose_name_plural': 'Mensagens de Contato Profissional',
            },
        ),
    ]
